services:
  application-db:
    image: 'mysql:8.4'
    environment:
      - 'MYSQL_DATABASE=monitor_preco'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'

  monitor:
    build: .
    environment:
      MONITOR_INTERVAL: 3600000