version: '3.8'

services:
  application-db:
    image: mysql:8.4
    environment:
      - 'MYSQL_DATABASE=monitor_preco'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - monitor-network

  monitor:
    build: .
    ports:
      - '8004:8004'
    environment:
      MONITOR_INTERVAL: 3600000
      SERVER_PORT: 8004
      DB_HOST: application-db
      DB_PORT: 3306
      DB_NAME: monitor_preco
      DB_USER: myuser
      DB_PASS: secret
    depends_on:
      - application-db
    networks:
      - monitor-network

volumes:
  db-data:

networks:
  monitor-network:
    driver: bridge